# Generated by Django 5.2.9 on 2025-12-21 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("creator_telegram_id", models.CharField(max_length=100)),
                (
                    "creator_telegram_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("num_teams", models.IntegerField(default=2)),
                ("winning_score", models.IntegerField(default=50)),
                ("penalty_for_skip", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for players"),
                            ("playing", "Playing"),
                            ("finished", "Finished"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("current_round", models.IntegerField(default=0)),
                ("current_team_index", models.IntegerField(default=0)),
                ("current_explainer_index_in_team", models.IntegerField(default=0)),
                (
                    "current_word",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("round_start_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("words_in_round_guessed", models.JSONField(default=list)),
                ("words_in_round_skipped", models.JSONField(default=list)),
                ("is_ending_round", models.BooleanField(default=False)),
                ("last_timer_end", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
                ("index", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.room"
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "unique_together": {("room", "index")},
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.CharField(max_length=100)),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.room"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.team",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("room", "telegram_id")},
            },
        ),
    ]
