# Generated by Django 5.2.9 on 2025-12-12 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creator_telegram_id", models.CharField(max_length=100)),
                (
                    "creator_telegram_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("num_teams", models.IntegerField(default=2)),
                ("winning_score", models.IntegerField(default=50)),
                ("penalty_for_skip", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for players"),
                            ("playing", "Playing"),
                            ("finished", "Finished"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("current_round", models.IntegerField(default=0)),
                ("current_team_index", models.IntegerField(default=0)),
                ("current_explainer_index_in_team", models.IntegerField(default=0)),
                (
                    "current_word",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("round_start_time", models.DateTimeField(blank=True, null=True)),
                ("words_in_round_guessed", models.JSONField(default=list)),
                ("words_in_round_skipped", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
                ("index", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.room"
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "index")},
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.CharField(max_length=100)),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.room"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "telegram_id")},
            },
        ),
    ]
